version: '3.9'

services:

  web:
    container_name: my-awesome-app-tph
    image: 55e02b60b3fe:latest
    ports:
      - '8080:80'
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules