version: '3.9'

services:

  my-awesome-app-tph_my-awesome-app-tph:
    container_name: my-awesome-app-tph_my-awesome-app-tph
    image: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
    ports:
      - '80:8080'

  my-awesome-app-tph-test:
    container_name: my-awesome-app-tph-test
    image: 
    volumes:
    ports:
      - '80:8080'

    command: ["npm", "run", "test"]