version: '3.9'

services:

  my-awesome-app-tph:
    container_name: my-awesome-app-tph
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
     - "8080:80"
    volumes:
      - '/app/node_modules'
      - .:/app
