version: '3.9'

services:

  my-awesome-app-tph:
    container_name: my-awesome-app-tph
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
     - "8080:80"
    volumes:
      - '/app/node_modules'
      - .:/app
  Single:
    container_name: frontend
    restart: always
  Multi:
    container_name: server
    restart: always
    build:
      context: server
      args:
        NODE_PORT: 3000
    ports:
      - 3000:3000
