version: '3.9'

services:

  my-awesome-app-tph:
    container_name: my-awesome-app-tph
    image: 55e02b60b3fe
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
    - .:/app
    - '/app/node_modules'
    ports:
      - '3002:3000'

  my-awesome-app-tph-test:
    container_name: my-awesome-app-tph-test
    image: 
    volumes:
     - .:/app
     - '/app/node_modules'
    command: ["npm", "run", "test"]