version: '3.9'

services:

  web:
    container_name: my-awesome-app-tph
    image: c0f11a3adb84:latest
    ports:
      - '8080:80'
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules