name: Deploy Node on AWS 

env:
  APP_NAME: my-awesome-app-tph
  AWS_REGION: us-east-1
  AWS_PLATFORM: Docker
  PIPELINE_ID: $GITHUB_RUN_ID-$GITHUB_RUN_NUMBER
  DATE_STAMP: $(date +%s)

on:
  workflow_dispatch:

jobs:
  deploy_aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials

        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Version Label
        run: |
          echo "aws_version_label=${{env.APP_NAME}}-${{env.PIPELINE_ID}}" >> $GITHUB_ENV
          echo "date-stamp=${{env.DATE_STAMP}}" >> $GITHUB_ENV
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{env.APP_NAME}}
          environment_name: Myawesomeapptph-env
          version_label: ${{env.date-stamp}}
          region: ${{env.AWS_REGION}}
          deployment_package: docker-compose.yml
